# Generated by Django 3.1.2 on 2020-11-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamente',
            new_name='Departamento',
        ),
    ]
