# Generated by Django 3.1.2 on 2020-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20201124_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo'),
        ),
    ]
